version = 0.1
[default.deploy.parameters]
stack_name = "code-stats"
resolve_s3 = true
s3_prefix = "code-stats"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
