AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  code-stats
Globals:
  Function:
    Timeout: 10

Resources:
  CodeStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CodeStatsApi:
          Type: Api
          Properties:
            Path: /code-stats
            Method: get
      Environment:
        Variables:
          WAKATIME_API_KEY: ""
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  CodeStatsApi:
    Description: "API Gateway endpoint URL for Prod stage for CodeStats function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/code-stats"
  CodeStatsFunction:
    Description: "CodeStats Lambda Function ARN"
    Value: !GetAtt CodeStatsFunction.Arn
  CodeStatsFunctionIamRole:
    Description: "Implicit IAM Role created for Code Stats function"
    Value: !GetAtt CodeStatsFunctionRole.Arn
