AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  activities
Globals:
  Function:
    Timeout: 10

Resources:
  TimeEntriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TimeEntriesApi:
          Type: Api
          Properties:
            Path: /activities
            Method: get
      Environment:
        Variables:
          TOGGL_API_KEY: ""
          TOGGL_WORKSPACE_ID: ""
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  TimeEntriesApi:
    Description: "API Gateway endpoint URL for Prod stage for Time Entries function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/activities"
  TimeEntriesFunction:
    Description: "Time Entries Lambda Function ARN"
    Value: !GetAtt TimeEntriesFunction.Arn
  TimeEntriesFunctionIamRole:
    Description: "Implicit IAM Role created for Time Entries function"
    Value: !GetAtt TimeEntriesFunctionRole.Arn
