AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  save-articles

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SaveArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_articles/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /save-articles
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SaveArticlesApi:
    Description: "API Gateway endpoint URL for Prod stage for Save Articles function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save-articles/"
  SaveArticlesFunction:
    Description: "Save Articles Lambda Function ARN"
    Value: !GetAtt SaveArticlesFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Save Articles function"
    Value: !GetAtt SaveArticlesFunctionRole.Arn
