services:
  local:
    image: amazon/dynamodb-local
    container_name: timetracking_dynamodb_local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/timetracking_dynamodb_local/data"
