version = 0.1
[default.deploy.parameters]
stack_name = "time-tracking"
resolve_s3 = true
s3_prefix = "time-tracking"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableName=\"TimeEntries\""
image_repositories = []
disable_rollback = true
confirm_changeset = true
