AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  exlibris

Globals:
  Function:
    Timeout: 3

Resources:
  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: books/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        BooksFunctionGet:
          Type: Api
          Properties:
            Path: /books
            Method: get
        BooksFunctionPost:
          Type: Api
          Properties:
            Path: /books
            Method: post
      Environment:
        Variables:
          DB_HOST: ""
          DB_USER: ""
          DB_PASSWORD: ""
          DB_NAME: ""
          DB_PORT: ""

Outputs:
  BooksFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage of Books Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exlibris/books"
  BooksFunction:
    Description: "Books Lambda Function ARN"
    Value: !GetAtt BooksFunction.Arn
  BooksFunctionIamRole:
    Description: "Implicit IAM Role created for Books function"
    Value: !GetAtt BooksFunction.Arn
